import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import AppProviders from "@/providers/AppProviders";
import { NextIntlClientProvider } from "next-intl";
import LocalSwitcher from "@/components/atoms/LocalSwitcher";
import { changeLocaleAction } from "@/i18n/locale";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${poppins.variable}  antialiased`}>
        <AppProviders>
          <NextIntlClientProvider>
            {children}
            <LocalSwitcher changeLocaleAction={changeLocaleAction} />
          </NextIntlClientProvider>
        </AppProviders>
      </body>
    </html>
  );
}
